language: go

sudo: false

go:
    - 1.17.x
    - 1.18.x
    - 1.19.x

script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.0
  - golangci-lint run ./...
  - go vet ./...
  - go test ./...

after_success:
- bash <(curl -s https://codecov.io/bash)
